sudo: false
language: php
php:
  - 5.6

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - bower_components
    - node_modules

install:
  - npm install
  - bower install

script:
  - gulp deploy
