sudo: false
language: node_js
node_js:
  - "0.12"

matrix:
  allow_failures:
    - php: nightly

cache:
  directories:
    - bower_components
    - node_modules

install:
  - npm install -g gulp
  - npm install -g bower
  - npm install
  - bower install

script:
  - gulp deploy
