sudo: false
language: node_js
node_js:
  - "0.12"

cache:
  directories:
    - bower_components
    - node_modules

before_install:
  # Set Git config
  - git config --global user.name "iwillhappy1314"
  - git config --global user.email "iwillhappy1314@gmail.com"
  - git config --global push.default simple

install:
  - npm install -g gulp
  - bower install

script:
  - ls -la
  - gulp deploy
